server:
  port: 8083

spring:
  application:
    name: avaliacao-service
  datasource:
    url: jdbc:postgresql://localhost:5432/transitamais
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: avaliacao
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: avaliacao
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/transitamais

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/