server:
  port: 8081

spring:
  application:
    name: usuario-service
  datasource:
    url: jdbc:postgresql://localhost:5432/transitamais
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: usuario
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: usuario
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/transitamais

keycloak:
  auth-server-url: http://localhost:8080
  realm: transitamais
  resource: usuario-service
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: usuario-service