server:
  port: 8084

spring:
  application:
    name: veiculo-service
  datasource:
    url: jdbc:postgresql://db:5432/transitamais
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: veiculo
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: veiculo
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/transitamais

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

ponto-service:
  url: http://ponto-service:8082